config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :users, except: [:index] do
    member do
      get :follow
      get :unfollow
    end
    resources :artworks do
      resources :comments, except: [:index]
    end
  end
  resources :sessions, only: [:create]

  get '/signup' => 'users#new'
  get '/signin' => 'sessions#new'
  delete '/signout' => 'sessions#destroy'
  get '/random' => 'welcome#random'
  get '/search' => 'artworks#search'

  get '/users/:id/subscriptions' => 'users#subscriptions'
  get '/users/:id/followers' => 'users#followers'
  get '/users/:id/block' => 'users#block'
  get '/users/:id/unblock' => 'users#unblock'

end

app/models/artwork.rb
class Artwork < ActiveRecord::Base
  belongs_to :user

  has_many :comments, dependent: :destroy

  validates :user, presence: true
  validates :title, presence: true

  has_attached_file :art_image, :styles => { :medium => "500x700>", :thumb => "200x200>" }, :default_url => ""
  validates_attachment_content_type :art_image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController
  before_action(:load_user, only: [:index, :new, :create, :show, :edit, :update, :destroy] )
  before_action :require_current_user, except: [:index, :show, :search]

  before_action(:load_artwork, { only: [:edit, :update, :show, :destroy] })

  def index
    page_user = User.find_by(id: params[:user_id])
    @artworks = page_user.artworks.reverse
  end

  def show
    if params[:user_id]
      @page_user = User.find_by(id: params[:user_id])
      @artwork = Artwork.find(params[:id])
      @comments = @artwork.comments
    end
  end

  def new
    @artwork = Artwork.new
  end

  def create
    @artwork = Artwork.new(artwork_params)
    @artwork.user = @user
    @artwork.save

    redirect_to user_artwork_path(@user, @artwork)
  end

  def edit
  end

  def update
    @artwork.update(artwork_params)
    redirect_to user_artwork_path(@user, @artwork)
  end

  def destroy
    if params[:user_id]
      Artwork.find(params[:id]).destroy
      redirect_to user_artworks_path(@user)
    end
  end

  def search
    @search_terms = params[:q].downcase.split(" ")
    @all_artwork = Artwork.all

    @results = @all_artwork.select do |artwork|

      title_words = artwork.title.downcase.gsub(/[^a-z0-9\s]/i, '').split(" ")

      description_words = artwork.description.downcase.gsub(/[^a-z0-9\s]/i, '').split(" ")

      !(title_words & @search_terms).empty? || !(description_words & @search_terms).empty?
    end

  end


  private

    def load_user
      return @user = User.find_by(id: params[:user_id])
    end

    def load_artwork
    return @artwork = Artwork.find_by(id: params[:id])
    end

    def artwork_params
      params.require(:artwork).permit(:title, :description, :image_url, :art_image, :user_id)
    end

    def require_current_user
      if !current_user?(@user)
        redirect_to root_path
      end
    end

end

app/views/artworks/_artwork.html.erb
<p><%= link_to artwork.title, user_artwork_path(artwork.user, artwork), :class => "art_title" %></p>

<% if artwork.image_url != "" %>
  <p><a href='/users/<%= artwork.user.id.to_s %>/artworks/<%= artwork.id.to_s %>'><%= image_tag artwork.image_url, width: "500px" %></a></p>
<% elsif artwork.art_image %>
  <p><a href='/users/<%= artwork.user.id.to_s %>/artworks/<%= artwork.id.to_s %>'><%= image_tag artwork.art_image.url(:medium) %></a></p>
<% end %>

<p><b>Description:</b> <%= artwork.description %></p>
<p><b>Uploaded:</b> <%= artwork.created_at.strftime("%b %d, %Y") %></p>

app/views/artworks/_artwork_form.html.erb
<p><%= link_to artwork.title, user_artwork_path(artwork.user, artwork), :class => "art_title" %></p>

<% if artwork.image_url != "" %>
  <p><a href='/users/<%= artwork.user.id.to_s %>/artworks/<%= artwork.id.to_s %>'><%= image_tag artwork.image_url, width: "500px" %></a></p>
<% elsif artwork.art_image %>
  <p><a href='/users/<%= artwork.user.id.to_s %>/artworks/<%= artwork.id.to_s %>'><%= image_tag artwork.art_image.url(:medium) %></a></p>
<% end %>

<p><b>Description:</b> <%= artwork.description %></p>
<p><b>Uploaded:</b> <%= artwork.created_at.strftime("%B %d, %Y") %></p>

app/views/artworks/_form.html.erb
<%= form_for [@user, @artwork] do |f| %>

  <p><%= f.label :title %>
    <%= f.text_field :title %></p>

  <p><%= f.label :description %>
    <%= f.text_field :description %></p>

  <p>
    <%= f.label :image_url %>
    <%= f.text_field :image_url %>
  </p>

  <p>
    <%= f.label :art_image %>
    <%= f.file_field :art_image %>
  </p>

  <%= f.submit "Submit", id: "submit" %>
<% end %>

<p><a href="/users/<%= @user.id %>/artworks" class="main_link">Cancel</a></p>

app/views/artworks/_user_artwork.html.erb
<p>By <a href="/users/<%= page_user.id %>"><%= artwork.user.first_name %> <%= artwork.user.last_name %></a></p>

<% if artwork.image_url != "" %>
  <p><%= image_tag artwork.image_url, width: "500px" %></p>
<% elsif artwork.art_image %>
  <p><%= image_tag artwork.art_image.url(:medium) %></p>
<% end %>

<p><b>Description:</b> <%= artwork.description %></p>
<p><b>Uploaded:</b> <%= artwork.created_at.strftime("%b %d, %Y") %></p>

app/views/artworks/_user_artwork_form.html.erb
<p>By <a href="/users/<%= page_user.id %>"><%= artwork.user.first_name %> <%= artwork.user.last_name %></a></p>

<% if artwork.image_url != "" %>
  <p><%= image_tag artwork.image_url, width: "500px" %></p>
<% elsif artwork.art_image %>
  <p><%= image_tag artwork.art_image.url(:medium) %></p>
<% end %>

<p><b>Description:</b> <%= artwork.description %></p>
<p><b>Uploaded:</b> <%= artwork.created_at.strftime("%B %d, %Y") %></p>

app/views/artworks/edit.html.erb
<div class="page">
  <%= render "form" %>
</div>

app/views/artworks/index.html.erb
<div class="page">
  <h1><%= @user.first_name %> <%= @user.last_name %>'s Gallery</h1>

  <ul>
    <% @artworks.each do |artwork| %>
      <li>
        <%= render partial: 'artwork_form', locals: { artwork: artwork } %>
      </li>
    <% end %>
  </ul>

  <p><%= link_to "Upload Artwork", new_user_artwork_path(@user), :class => "main_link"  %></p>
</div>

app/views/artworks/new.html.erb
<div class="page">
  <%= render "form" %>
</div>

app/views/artworks/search.html.erb
<div class="page">

  <h1>Search Results for "<span class="search_query"><%= params[:q] %></span>":</h1>
    <ul>
    <% @results.each do |artwork| %>
      <li>
        <p>By <a href="/users/<%= artwork.user.id %>"><%= artwork.user.first_name %> <%= artwork.user.last_name %></a></p>
        <%= render partial: 'artwork_form', locals: { artwork: artwork } %>
      </li>
    <% end %>
    </ul>

    <p><a href="/" class="main_link">Back</a></p>
</div>

app/views/artworks/show.html.erb
<div class="page">
  <% if params[:user_id] %>
	<h1><%= @artwork.title %></h1>

	<%= render partial: 'user_artwork_form', locals: { artwork: @artwork, page_user: @page_user } %>

	<p>
	  <% if signed_in? %>
		<%= link_to "Add Comment", new_artwork_comment_path(@artwork), :class => "main_link" %>
	  <% end %>
	</p>

	<% if @page_user == current_user %>
	  <p><%= link_to "Edit", edit_user_artwork_path(@user, @artwork), :class => "main_link" %></p>
	  <p>
		<%= form_for [@user, @artwork], method: 'delete' do |f| %>
		  <%= f.submit "Remove Artwork", id: "destroy" %>
		<% end %>
	  </p>
	<% end %>

    <ul>
      <% if @comments %>
        <% @comments.each do |comment| %>
          <li>
            <%= render partial: 'comments/comment_display_form', locals: { comment: comment } %>
          </li>
        <% end %>
      <% end %>
    </ul>

  <% end %>
</div>