config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :users, except: [:index] do
    member do
      get :follow
      get :unfollow
    end
    resources :artworks do
      resources :comments, except: [:index]
    end
  end
  resources :sessions, only: [:create]

  get '/signup' => 'users#new'
  get '/signin' => 'sessions#new'
  delete '/signout' => 'sessions#destroy'
  get '/random' => 'welcome#random'
  get '/search' => 'artworks#search'

  get '/users/:id/subscriptions' => 'users#subscriptions'
  get '/users/:id/followers' => 'users#followers'
  get '/users/:id/block' => 'users#block'
  get '/users/:id/unblock' => 'users#unblock'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :artworks, dependent: :destroy

  has_many :users, through: :follows

  belongs_to :user

  acts_as_follower
  acts_as_followable

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" , :tiny => "25x25"}, :default_url => "http://codegurl.com/wp-content/uploads/2014/05/egg.jpg"

  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  # Add handlers to run when creating and saving
  before_create :create_remember_token
  before_save :normalize_fields

  # Validate name:
  validates :first_name,
    presence: true,
    length: { maximum: 50 }

  # Validate name:
  validates :last_name,
    presence: true,
    length: { maximum: 50 }

  # Validate email address:
  validates :email,
    presence: true,
    uniqueness: { case_sensitive: false },
    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }


  # Secure password features:
  has_secure_password


  # Create a new remember token for a user:
  def self.new_remember_token
    SecureRandom.urlsafe_base64
  end

  # Hash a token:
  def self.hash_token(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

  # Creates a new session token for the user:
  def create_remember_token
    self.remember_token = User.hash_token(User.new_remember_token)
  end

  # Normalize fields for consistency:
  def normalize_fields
    self.email.downcase!
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_signin, except: [:new, :create, :show, :follow, :unfollow, :subscriptions, :followers]
  before_action :find_user, only: [:show, :edit, :update, :destroy, :follow, :unfollow, :subscriptions, :followers, :block, :unblock]
  before_action :require_current_user, except: [:new, :create, :show, :subscriptions, :followers, :follow, :unfollow, :block, :unblock]


  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in @user
      redirect_to @user
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path
  end

  def follow

    current_user.follow(@user)
    redirect_to user_path(@user)

  end

  def unfollow

    current_user.stop_following(@user)
    redirect_to user_path(@user)

  end

  def subscriptions
    followed_artworks = []

    @user.all_following_users.each do |following|
      following.artworks.each do |artwork|
        followed_artworks.push(artwork)
      end
    end

    @recent_artworks = (followed_artworks.sort_by {|artwork| artwork.created_at }).reverse
  end

  def followers
    @sorted_followers = @user.followers.sort_by{ |user| user.first_name }
  end

  def block
    current_user.block(@user)
    redirect_to user_path(@user)
  end

  def unblock
    current_user.unblock(@user)
    redirect_to user_path(@user)
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(
      :first_name,
      :last_name,
      :email,
      :password,
      :password_confirmation,
      :avatar
    )
  end

  def require_current_user
    if !current_user?(@user)
      redirect_to root_path
    end
  end
end

app/views/users/_thumbnails_form.html.erb
<a href='/users/<%= follower.id.to_s %>'><%= image_tag(follower.avatar.url(:tiny), :class => "icon") %></a>
<a href='/users/<%= follower.id.to_s %>' class="username"><%= follower.first_name %> <%= follower.last_name %></a></p>

app/views/users/_user_form.html.erb
<% if @user.errors.any? %>
  <b>Errors:</b>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
</ul>
<% end %>

<%= form_for @user do |f| %>
  <p><%= f.label :first_name %>
    <%= f.text_field :first_name %></p>

  <p><%= f.label :last_name %>
    <%= f.text_field :last_name %></p>

  <p><%= f.label :email %>
    <%= f.text_field :email %></p>

  <p><%= f.label :password %>
    <%= f.password_field :password %></p>

  <p><%= f.label :password_confirmation, 'Confirm Password' %>
  <%= f.password_field :password_confirmation, :class => "field" %></p>

  <p>
    <%= f.label :avatar %>
    <%= f.file_field :avatar %>
  </p>

  <p><%= f.submit "Submit", id: 'submit' %></p>
<% end %>

app/views/users/edit.html.erb
<div class="page">
  <h1>Edit <%= @user.first_name %> <%= @user.last_name %>'s Account Details</h1>
  <%= render "user_form" %>

  <hr>

  <%= form_for @user, method: 'delete' do |f| %>
    <%= f.submit "Delete", :class => "delete_button" %>
  <% end %>

  <hr>

  <%= link_to "Cancel", user_path(@user), :class => "main_link"  %>
</div>

app/views/users/followers.html.erb
<div class="page">
  <h1><%= @user.first_name %> <%= @user.last_name %>'s Followers</h1>

  <ul>
  <% @user.user_followers.each do |follower| %>
    <li>
      <h2>
        <a href='/users/<%= follower.id.to_s %>'><%= image_tag(follower.avatar.url(:tiny), :class => "icon") %></a>
        <a href='/users/<%= follower.id.to_s %>'><%= follower.first_name %> <%= follower.last_name %></a>
      </h2>

      <% if follower.artworks != [] %>
        <h3>Latest Project</h3>

        <%= render partial: '/artworks/artwork_form', locals: { artwork: follower.artworks[-1] } %>
      <% end %></li>

  <% end %>
  </ul>

</div>

<div class="followings" role="complementary">
  <h2>Followers:</h2>

  <ul class="users-list">
    <% @sorted_followers.each do |follower| %>
      <li>
        <p>
          <%= render partial: 'thumbnails_form', locals: { follower: follower } %>
      </li>
    <% end %>
  </ul>
</div>

app/views/users/new.html.erb
<div class="page">
  <h1>Create a User</h1>
  <%= render "user_form" %>
</div>

app/views/users/show.html.erb
<div class="page">
  <h1><%= @user.first_name %> <%= @user.last_name %></h1>


  <%= image_tag @user.avatar.url(:medium) %>

  <p><b>Email:</b> <%= @user.email %></p>
  <p><b>Joined:</b> <%= @user.created_at.strftime("%b %d, %Y") %></p>
  <p><b>Followers:</b> <a href="/users/<%= @user.id.to_s %>/followers"><%= @user.count_user_followers.to_s %></a></p>
  <p><b>Following:</b> <a href="/users/<%= @user.id.to_s %>/subscriptions"><%= @user.follow_count.to_s %></a></p>

  <% if current_user == @user %>
    <p><%= link_to "Edit", edit_user_path(@user), :class => "main_link"  %></p>
  <% end %>

  <p><%= link_to "Gallery", user_artworks_path(@user), :class => "main_link" %></p>

  <% if current_user %>
   <% if current_user != @user %>
      <% if @user.followed_by?(current_user) %>
        <p><%= link_to "Unfollow", unfollow_user_path(@user), :class => "main_link" %></p>
      <% else %>
        <p><%= link_to "Follow", follow_user_path(@user), :class => "main_link" %></p>
      <% end %>

      <p>
        <a href="/users/<%= @user.id %>/block" class="main_link">Block</a> | <a href="/users/<%= @user.id %>/unblock" class="main_link">Unblock</a>
      </p>
    <% end %>
  <% end %>


</div>

app/views/users/subscriptions.html.erb
<div class="page">
  <h1><%= @user.first_name %> <%= @user.last_name %>'s Subscriptions</h1>
  <h2>Latest Artwork</h2>

  <% if @recent_artworks != [] %>
  <ul>
    <% @recent_artworks.first(20).each do |artwork| %>

      <li><h3><%= artwork.title %></h3>
        <p>By <a href='/users/<%= artwork.user.id.to_s %>'><%= artwork.user.first_name %> <%= artwork.user.last_name %></a></p>

        <% if artwork.image_url != "" %>
          <p><a href='/users/<%= artwork.user.id.to_s %>/artworks/<%= artwork.id.to_s %>'><%= image_tag artwork.image_url, width: "500px" %></a></p>
        <% elsif artwork.art_image %>
          <p><a href='/users/<%= artwork.user.id.to_s %>/artworks/<%= artwork.id.to_s %>'><%= image_tag artwork.art_image.url(:medium) %></a></p>
        <% end %>

        <p>Uploaded: <%= artwork.created_at.strftime("%b %d, %Y") %></li>

    <% end %>

    <br>
  </ul>
  <% end %>


</div>

<div class="followings" role="complementary">
  <h2>Following:</h2>

  <ul class="users-list">
    <% @sorted_followings = @user.all_following_users.sort_by{ |user| user.first_name } %>
    <% @sorted_followings.each do |follower| %>
      <li>
        <%= render partial: 'thumbnails_form', locals: { follower: follower } %>
      </li>
    <% end %>
  </ul>
</div>