config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :users, except: [:index] do
    member do
      get :follow
      get :unfollow
    end
    resources :artworks do
      resources :comments, except: [:index]
    end
  end
  resources :sessions, only: [:create]

  get '/signup' => 'users#new'
  get '/signin' => 'sessions#new'
  delete '/signout' => 'sessions#destroy'
  get '/random' => 'welcome#random'
  get '/search' => 'artworks#search'

  get '/users/:id/subscriptions' => 'users#subscriptions'
  get '/users/:id/followers' => 'users#followers'
  get '/users/:id/block' => 'users#block'
  get '/users/:id/unblock' => 'users#unblock'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @user = current_user
  end

  def random
    @all_artworks = Artwork.all

  end

end

app/views/welcome/index.html.erb
<div class="page">
  <h1>Artbook</h1>

  <p class="intro"><b>Artbook</b> is an online artwork and photography portfolio. Follow your favorite portfolios or create one of your own.</p>
  <p class="intro">Begin by searching through the art on this site or click on <b>Randomize</b> for a surprise.</p>
  <%= form_tag("/search", method: "get") do %>
    <%= label_tag(:q, "Search for Art:") %>
    <%= text_field_tag(:q) %>
    <%= submit_tag("Search", :class => "search") %>
  <% end %>


  <p><%= link_to "Randomize", random_path, :class => "main_link" %></p>
  <p>
    <% if signed_in? %>
      <%= link_to "Upload Artwork", new_user_artwork_path(@user), :class => "main_link" %>
    <% end %>
  </p>
</div>

app/views/welcome/random.html.erb
<div class="page">
  <h1>Random Artwork</h1>

  <% if @all_artworks != [] %>
    <% random_artwork = @all_artworks.sample %>
    <h2><%= random_artwork.title %></h2>

    <p>By <a href="/users/<%= random_artwork.user.id %>"><%= random_artwork.user.first_name %> <%= random_artwork.user.last_name %></a></p>

    <% if random_artwork.image_url != "" %>
      <p><a href="/users/<%= random_artwork.user.id %>/artworks/<%= random_artwork.id %>"><%= image_tag random_artwork.image_url, width: "500px" %></a></p>
    <% elsif random_artwork.art_image %>
      <p><%= image_tag random_artwork.art_image.url(:medium) %></p>
    <% end %>

    <p><b>Description:</b> <%= random_artwork.description %></p>
    <p><b>Uploaded:</b> <%= random_artwork.created_at.strftime("%b %d, %Y") %></p>
  <% else %>
    <h2>There are no artworks to display.</h2>
  <% end %>



  <p><%= link_to "Refresh Page", random_path, :class => "main_link" %></p>
  <p><%= link_to "Back", root_path, :class => "main_link" %></p>
</div>