config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :users, except: [:index] do
    member do
      get :follow
      get :unfollow
    end
    resources :artworks do
      resources :comments, except: [:index]
    end
  end
  resources :sessions, only: [:create]

  get '/signup' => 'users#new'
  get '/signin' => 'sessions#new'
  delete '/signout' => 'sessions#destroy'
  get '/random' => 'welcome#random'
  get '/search' => 'artworks#search'

  get '/users/:id/subscriptions' => 'users#subscriptions'
  get '/users/:id/followers' => 'users#followers'
  get '/users/:id/block' => 'users#block'
  get '/users/:id/unblock' => 'users#unblock'

end

app/views/common/_signout.html.erb
<% if signed_in? %>

  <%= form_for :session, url: signout_path, method: 'delete' do |f| %>
    Signed in as <%= link_to current_user.first_name, current_user %>
    <%= f.submit "Sign Out", id: 'signout' %>
  <% end %>

  <p><div class="profile"><a href="/users/<%= current_user.id %>"><%= image_tag current_user.avatar.url(:thumb) %></div></a></p>

  <p><%= link_to "My Gallery", user_artworks_path(current_user), :class => "my_links" %></p>

  <p><a href='/users/<%= current_user.id.to_s %>/subscriptions' class="my_links">My Subscriptions (<%= current_user.follow_count.to_s %>)</a></p>
  <p><a href='/users/<%= current_user.id.to_s %>/followers' class="my_links">My Followers (<%= current_user.followers_by_type_count('User').to_s %>)</a></p>

<% else %>

  <%= link_to "Sign In", signin_path %> | <%= link_to "Sign Up", signup_path %>

<% end %>